// Copyright 2021 Lorena Munoz. //
// All rights reserved. Lorena Projects. //

class HistoryBank {
//  final title, description;
  List<String> bank = [
    //************** 1st*************************
    'Add_Content_Max_190_Characters',
    //**************************************************************************************************************************************************
    //*********************2nd ************************************************
    "In 1865, Richard Millar Devens presented the phrase “Business Intelligence” (BI) in the Cyclopædia of Commercial and Business Anecdotes. He was using it to describe how Sir Henry Furnese, a banker, profited from information by gathering and acting on it before his competition. More recently, in 1958, an article was written by an IBM computer scientist named Hans Peter Luhn, describing the potential of gathering Business Intelligence (BI) through the use of technology. Business intelligence, as it is understood today, uses technology to gather and analyze data, translate it into useful information, and act on it “before the competition.” Essentially, the modern version of BI focuses on technology a way to make decisions quickly and efficiently, based on the right information at the right time. In 1968, only individuals with extremely specialized skills could translate data into usable information.",
    //*********************************************************
    "As the hype around AI has accelerated, vendors have been scrambling to promote how their products and services use AI. Often what they refer to as AI is simply one component of AI, such as machine learning. AI requires a foundation of specialized hardware and software for writing and training machine learning algorithms. No one programming language is synonymous with AI, but a few, including Python, R and Java, are popular. ", //*********************************************************
    "Business Intelligence, as a technological concept, began shortly after the 1988 international conference, The Multiway Data Analysis Consortium, held in Rome. The conclusions reached at this conference jump-started efforts for simplifying BI analysis, while making it more user-friendly. A large number of BI businesses started up in response to the conference’s conclusions, with each new business offering new BI tools. During this period, there were two basic functions of BI: producing data and reports, and organizing and visualizing it in a presentable way. In the late 1990s and early 2000s, BI services began providing simplified tools, allowing decision makers to become more self-sufficient. The tools were easier to use, provided the functionality needed, and were very efficient. Business people could now gather data and gain insights by working directly with the data.", //*********************************************************
    "Business Intelligence, BI services began providing simplified tools, allowing decision makers to become more self-sufficient. The tools were easier to use, provided the functionality needed, and were very efficient. Business people could now gather data and gain insights by working directly with the data.", //*********************************************************
    "Automation. When paired with AI technologies, automation tools can expand the volume and types of tasks performed. An example is robotic process automation (RPA), a type of software that automates repetitive, rules-based data processing tasks traditionally done by humans. When combined with machine learning and emerging AI tools, RPA can automate bigger portions of enterprise jobs, enabling RPA's tactical bots to pass along intelligence from AI and respond to process changes.", //*********************************************************
    "Business Intelligence, as a technological concept, began shortly after the 1988 international conference, The Multiway Data Analysis Consortium, held in Rome. The conclusions reached at this conference jump-started efforts for simplifying BI analysis, while making it more user-friendly. A large number of BI businesses started up in response to the conference’s conclusions, with each new business offering new BI tools. During this period, there were two basic functions of BI: producing data and reports, and organizing and visualizing it in a presentable way. In the late 1990s and early 2000s, BI services began providing simplified tools, allowing decision makers to become more self-sufficient. The tools were easier to use, provided the functionality needed, and were very efficient. Business people could now gather data and gain insights by working directly with the data.", //*********************************************************
    "As the hype around AI has accelerated, vendors have been scrambling to promote how their products and services use AI. Often what they refer to as AI is simply one component of AI, such as machine learning. AI requires a foundation of specialized hardware and software for writing and training machine learning algorithms. No one programming language is synonymous with AI, but a few, including Python, R and Java, are popular.", //*********************************************************
    "As the hype around AI has accelerated, vendors have been scrambling to promote how their products and services use AI. Often what they refer to as AI is simply one component of AI, such as machine learning. AI requires a foundation of specialized hardware and software for writing and training machine learning algorithms. No one programming language is synonymous with AI, but a few, including Python, R and Java, are popular.", //*********************************************************
    "Business Intelligence, as a technological concept, began shortly after the 1988 international conference, The Multiway Data Analysis Consortium, held in Rome. The conclusions reached at this conference jump-started efforts for simplifying BI analysis, while making it more user-friendly. A large number of BI businesses started up in response to the conference’s conclusions, with each new business offering new BI tools. During this period, there were two basic functions of BI: producing data and reports, and organizing and visualizing it in a presentable way. In the late 1990s and early 2000s, BI services began providing simplified tools, allowing decision makers to become more self-sufficient. The tools were easier to use, provided the functionality needed, and were very efficient. Business people could now gather data and gain insights by working directly with the data.", //*********************************************************
    "Business Intelligence, as a technological concept, began shortly after the 1988 international conference, The Multiway Data Analysis Consortium, held in Rome. The conclusions reached at this conference jump-started efforts for simplifying BI analysis, while making it more user-friendly. A large number of BI businesses started up in response to the conference’s conclusions, with each new business offering new BI tools. During this period, there were two basic functions of BI: producing data and reports, and organizing and visualizing it in a presentable way. In the late 1990s and early 2000s, BI services began providing simplified tools, allowing decision makers to become more self-sufficient. The tools were easier to use, provided the functionality needed, and were very efficient. Business people could now gather data and gain insights by working directly with the data.", //*********************************************************
    "Business Intelligence, as a technological concept, began shortly after the 1988 international conference, The Multiway Data Analysis Consortium, held in Rome. The conclusions reached at this conference jump-started efforts for simplifying BI analysis, while making it more user-friendly. A large number of BI businesses started up in response to the conference’s conclusions, with each new business offering new BI tools. During this period, there were two basic functions of BI: producing data and reports, and organizing and visualizing it in a presentable way. In the late 1990s and early 2000s, BI services began providing simplified tools, allowing decision makers to become more self-sufficient. The tools were easier to use, provided the functionality needed, and were very efficient. Business people could now gather data and gain insights by working directly with the data.", //*********************************************************
    "Business Intelligence, as a technological concept, began shortly after the 1988 international conference, The Multiway Data Analysis Consortium, held in Rome. The conclusions reached at this conference jump-started efforts for simplifying BI analysis, while making it more user-friendly. A large number of BI businesses started up in response to the conference’s conclusions, with each new business offering new BI tools. During this period, there were two basic functions of BI: producing data and reports, and organizing and visualizing it in a presentable way. In the late 1990s and early 2000s, BI services began providing simplified tools, allowing decision makers to become more self-sufficient. The tools were easier to use, provided the functionality needed, and were very efficient. Business people could now gather data and gain insights by working directly with the data.",
  ];
  String title = 'Add_Title';
//
//  HistoryBank({this.title, this.description});
}
